### ISSUE TITLE
Default colors for colorcolumns blend 1:1 with the bg color

### ISSUE THREAD

**Issue by effinsky** [kaiuri/onigiri.nvim#2]
As in the img below, the default colors for colorcolumns in Mariana blend 100% with the background color. Would be swell to get those to be some other shade, perhaps the one used by the line highlight or yet a different one. 

<img width="910" alt="Screenshot 2022-11-13 at 16 38 37" src="https://user-images.githubusercontent.com/54535543/201530715-8c1e5e25-b4a1-4c55-b6db-ea632e260098.png">

Thanks in advance!

**Comment by kaiuri** [comment]
@effinsky Thanks for pointing it out. It seems that when `cursorline`, `cursorcolumn` and/or `signcolumn` options are set, `Shade.{default,emphasis}` disrupts highlighting. It seems standard not to add background highlighting to syntax elements, so I removed shade from those.

**Comment by effinsky** [comment]
Yup, very cool. And thanks for the quick response. One of my face themes ever (and my eyes agree!): 

<img width="1002" alt="Screenshot 2022-11-14 at 10 01 54" src="https://user-images.githubusercontent.com/54535543/201618735-83e5e429-6534-4c6e-9ecb-9f507ad0a653.png">

**Comment by kaiuri** [comment]
Looks great! Good to know this plugin is serving its purpose.
