### ISSUE TITLE
can i create custom presets?

### ISSUE THREAD

**Issue by luxus** [kaiuri/onigiri.nvim#3]
can i have multiple presets created by me?
or can I only overwrite the default?

i run your theme in a lazy.nvim setup that change themes by sun dawn
```lua
  {
    "JManch/sunset.nvim",
    priority = 1000,
    lazy = false,
    dependencies = {
      "kaiuri/onigiri.nvim",
    },
    config = function()
      require("sunset").setup {
        latitude = 48.57,
        longitude = 8.51,
        day_callback = function()
          vim.g.onigiri = {
            theme = require("onigiri").presets.kaolin,
          }
        end,
        night_callback = function()
          vim.g.onigiri = {
            theme = require("onigiri").presets.moonlight,
          }
        end,
      }
    end,
  },
}
```
Now I want to add custom presets. Is this possible?
And I wonder about the dark and light variant are they auto generated? and i don't understand how to change theme

ps your theme is well done, all my plugins looking beautiful :D

**Comment by kaiuri** [comment]
Thank you, happy you like it. You can, @luxus, I have 8 myself.
There's a `load` function you can call and it will update your theme to use its arguments (a `vim.g.onigiri.theme`-like table), checkout the '[Wanna change it on the fly? :roller_coaster:](https://github.com/kaiuri/onigiri.nvim#wanna-change-it-on-the-fly-)' section of the `README.md` (just added it).

**Comment by luxus** [comment]
looks like i inspired u to the day and night feature
the great about sunset is that it loads on the fly, I use to use your way before

it's still a little confusing, to follow your examples, I would say. 
maybe a full example with comments makes more sense
I love how lazyvim did it..
https://www.lazyvim.org/configuration/examples

do you mind sharing your config? i like to see your 8 themes :D

**Comment by kaiuri** [comment]
@luxus I've added a [this](https://github.com/kaiuri/onigiri.nvim#how-does-it-work-) to the README. About my configuration, I'll need to clean it up "a bit" before sharing, but once I do, I'll let you know 😄

**Comment by luxus** [comment]
```lua
{
    "kaiuri/onigiri.nvim",
    init = function()
      vim.g.onigiri = {
        theme = {
          Background = {
            default = "#303841",
            emphasis = "#2e353e",
            muted = "#46525c",
          },
          Foreground = {
            default = "#d8dee9",
            emphasis = "#f7f7f7",
            muted = "#a6acb8",
            surface = "#46525c",
          },
          Shade = {
            default = "#2f373f",
            emphasis = "#2e363e",
          },
          Colors = {
            Accent = "#95B2D6",
            Caution = "#f9ae58",
            Danger = "#f97b58",
            Error = "#ec5f66",
            Hint = "#5fb4b4",
            Important = "#fac761",
            Info = "#99c794",
            Note = "#5c99d6",
            Trace = "#cc8ec6",
            Warn = "#ee932b",
          },
        },
      }
    end,
    config = function()
      local time = function() return tonumber(os.date "%H") end
      if time() >= 6 and time() <= 18 then
        vim.g.onigiri = {
          theme = require("onigiri").presets.mariana,
        }
      else
        vim.g.onigiri = {
          theme = require("onigiri").presets.moonlight,
        }
      end
    end,
    priority = 1000,
    lazy = false,
  }
  ```
  that's how I use it right now,
so can I create additional presets?

**Comment by kaiuri** [comment]
At the moment, you may

1. Place them into their own module inside your ` $XDG_CONFIG_HOME/nvim/lua/`
   folder and require them when setting `vim.g.onigiri`
2. Open a pull request to add them to this repo. In which case:
   - Add the preset's definition file to `presets/<preset-name>.lua`
   - Add an entry with their name to `lua/onigiri/presets/init.lua`
   ```lua
    local __presets = {
        "mariana",
        "gruvbox",
        "kaolin",
        "solarized",
        "moonlight",
        -- <preset-name>
    }
   ```
3. Open an issue with the preset definition and I'll add it for you.

**Comment by luxus** [comment]
ah okay, i thought i configure them with the setup()

in lazy.nvim its even easier i can set the plugin in dev mode https://github.com/folke/lazy.nvim#-plugin-spec
and clone it.
thanks for answering the questions.
